# -*- coding: utf-8 -*-
{
    "name": "Web Site Hino",
    "summary": """
        Sitio Web HINO
    """,
    "description": """
        
    """,
    "author": "",
    "website": "http://www.yourcompany.com",
    "contributors": [
        "nestoki",
        "luismdp05",
        "luisanamrs",
    ],
    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    "category": "Uncategorized",
    "version": "0.1",
    # any module necessary for this one to work correctly
    "depends": ["base", "crm", "website"],
    # always loaded
    "data": [
        "security/ir.model.access.csv",
        "views/home/index.xml",
        "views/nosotros/nosotros_tambor.xml",
        "views/nosotros/nosotros_hino.xml",
        "views/camiones/camiones.xml",
        "views/series/series.xml",
        "views/soporte/servicios.xml",
        "views/soporte/repuestos.xml",
        "views/soporte/mantenimiento_prepagado.xml",
        "views/soporte/free_service_program.xml",
        "views/soporte/eco_safety_drive.xml",
        "views/soporte/customer_care_clinics.xml",
        "views/contactenos/contactenos.xml",
        "views/novedades/novedades.xml",
        "views/novedades/novedades_news.xml",
        "views/sucursales/sucursales.xml",
        "views/politicas/politicas_privacidad.xml",
        "views/camion_views.xml",
        "views/info_contacto_views.xml",
        "views/novedades_views.xml",
        "views/slider_main_views.xml",
        "views/soporte_total_views.xml",
        "views/servicios_soporte_views.xml",
        "views/aplicacion_views.xml",
        "views/series_views.xml",
        "views/sucursales_views.xml",
        "views/servicios_views.xml",
        "views/cabina_views.xml",
        "views/eco_safety_drive_views.xml",
        "views/customer_care_clinic_views.xml",
        "views/repuestos_views.xml",
        "views/landing/landing-page1.xml",
        "views/landing/landing-page2.xml",
        "views/login/login.xml",
        "views/login/reset_password.xml",
        "views/login/auth_totp.xml",
        "views/servicios/tambor_services.xml",
        "views/sucursales/tambor_sucursales.xml",
        "views/contactenos/tambor_contacto.xml",
        "views/taller/tambor_taller.xml",
    ],
    "assets": {
        "website_hino.assets_frontend": [
            # Vistas frontend xml
            "website_hino/views/servicios/servicios_tambor.xml",
            "website_hino/views/home/index.xml",
            "website_hino/views/nosotros/nosotros_hino.xml",
            "website_hino/views/nosotros/nosotros_tambor.xml",
            "website_hino/views/camiones/camiones.xml",
            "website_hino/views/series/series.xml",
            "website_hino/views/soporte/servicios.xml",
            "website_hino/views/soporte/repuestos.xml",
            "website_hino/views/soporte/mantenimiento_prepagado.xml",
            "website_hino/views/soporte/free_service_program.xml",
            "website_hino/views/soporte/eco_safety_drive.xml",
            "website_hino/views/soporte/customer_care_clinics.xml",
            "website_hino/views/novedades/novedades.xml",
            "website_hino/views/novedades/novedades_news.xml",
            "website_hino/views/sucursales/sucursales.xml",
            "website_hino/views/contactanos/contactanos.xml",
            "website_hino/views/politicas/politicas_privacidad.xml",
            # Archivos frontend css
            "website_hino/static/src/css/index.css",
            "website_hino/static/src/css/modelos-camiones.css",
            "website_hino/static/src/css/soporte-total.css",
            "website_hino/static/src/css/novedades.css",
            "website_hino/static/src/css/formulario.css",
            "website_hino/static/src/css/camiones/camiones.css",
            "website_hino/static/src/css/nosotros/nosotros-hino.css",
            "website_hino/static/src/css/nosotros/nosotros-tambor.css",
            "website_hino/static/src/css/novedades/novedades.css",
            "website_hino/static/src/css/novedades/novedades_news.css",
            "website_hino/static/src/css/series/series.css",
            "website_hino/views/soporte/servicios.css",
            "website_hino/views/soporte/repuestos.css",
            "website_hino/views/soporte/mantenimiento_prepagado.css",
            "website_hino/views/soporte/free_service_program.css",
            "website_hino/views/soporte/eco_safety_drive.css",
            "website_hino/views/soporte/customer_care_clinics.css",
            "website_hino/static/src/css/sucursales/sucursales.css",
            "website_hino/static/src/css/contactenos/contactenos.css",
            "website_hino/static/src/css/swiper/swiper-bundle.min.css",
            "website_hino/static/src/css/font-awesome/font-awesome.min.css",
            "website_hino/static/src/css/login/login.css"
            # Archivos forntend js
            "website_hino/static/src/js/modelos-camiones.js",
            "website_hino/static/src/js/slider-soporte.js",
            "website_hino/static/src/js/camiones/btn-mostrar-ocultar.js",
            "website_hino/static/src/js/camiones/camiones.js",
            "website_hino/static/src/js/camiones/galeria.js",
            "website_hino/static/src/js/series/galeria.js",
            "website_hino/static/src/js/series/modal.js",
            "website_hino/static/src/js/series/series.js",
            "website_hino/static/src/js/soporte/galeria.js",
            "website_hino/static/src/js/soporte/mostrar-paquetes.js",
            "website_hino/static/src/js/soporte/planes.js",
            "website_hino/static/src/js/soporte/slider.js",
            "website_hino/static/src/js/swiper/slider.js",
            "website_hino/static/src/js/swiper/swiper-bundle.min.js",
            "website_hino/static/src/js/sucursales/sucursales.js",
            "website_hino/static/src/js/modelos-camiones.js",
            "website_hino/static/src/js/mostrar-footer.js",
            "website_hino/static/src/js/mostrar-responsive.js",
            "website_hino/static/src/js/slider-soporte.js",
        ],
    },
    # only loaded in demonstration mode
    "demo": [
        "demo/demo.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
